# Generated by Django 4.0.1 on 2022-01-21 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=30, message='Content should be at least 300 characters long!')]),
        ),
    ]
